import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

export default function Home() {
  const { data } = api.link.get.useQuery();

  return (
    <>
      <Head>
        <title>KnightHacks Link Tree</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-8 py-16">
        <div className="mx-auto flex max-w-screen-sm flex-col">
          <div className="mx-auto mb-8 flex flex-col items-center">
            <div className="mb-2 grid h-[100px] w-[100px] place-items-center rounded-full border text-center font-bold uppercase">
              KH
            </div>
            <div className="font-bold text-xl">@KnightHacks</div>
          </div>
          {/* Social Icons */}
          <ul></ul>
          {/* Links */}
          <ul className="flex flex-col gap-3">
            {data?.map((link) => (
              <li key={link.id}>
                <Link
                  href={link.url}
                  className="block w-full rounded-full border p-4 text-center"
                >
                  {link.name}
                </Link>
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
}

// function AuthShowcase() {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = api.post.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined }
//   );

//   return (
//     <div className="flex flex-col items-center justify-center gap-4">
//       <p className="text-center text-2xl text-white">
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage}</span>}
//       </p>
//       <button
//         className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//         onClick={sessionData ? () => void signOut() : () => void signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </button>
//     </div>
//   );
// }
